### ISSUE TITLE
Pushing toward a Hackage release

### ISSUE THREAD

**Issue by bitemyapp** [helium/postgresql-transactional#1]
We use Stack, so it's not a big deal to depend on a Git repository, but is there any interest in getting postgresql-transactional on Hackage?

If there's a way in which I could help with this, please let me know.

**Comment by reiddraper** [comment]
Sure thing.

**Comment by BardurArantsson** [comment]
Or, actually... have you approached the postgresql-simple maintainer about just merging this as an "optional extra" type module? It seems generally extremely useful and it doesn't seem like it would "pollute" postgresql-simple too much as it could be an entirely optional module.

**Comment by patrickt** [comment]
Uploaded to https://hackage.haskell.org/package/postgresql-transactional

**Comment by bitemyapp** [comment]
Thanks y'all :+1:

**Comment by reiddraper** [comment]
Note this version differs a bit from the previous versions that were in git for a bit, namely:

* The module name changed
* Queries now _always_ take their `input` as an argument before the `Query`
