### ISSUE TITLE
Replace the MonadReader instance with a more general version

### ISSUE THREAD

**Issue by jfischoff** [helium/postgresql-transactional#12]
The current MonadReader instance is specialized for the internal Connection state. However this makes PGTransactionT less useful as a generic transformer. A more general MonadReader instance would be something like 

``` haskell
instance MonadReader r m => MonadReader r (PGTransactionT m) where
```

To regain the current behavior a `getConnection` function could be added.

**Comment by reiddraper** [comment]
@jfischoff thanks, good idea. We'd be happy to accept a PR for this -- is this something you'd be interested in contributing? Otherwise we're happy to make the change.

**Comment by jfischoff** [comment]
I have made code change, I'll submit a PR tonight.
