### ISSUE TITLE
Missing execute_ 

### ISSUE THREAD

**Issue by jfischoff** [helium/postgresql-transactional#16]
`postgresql-transactional` exposes an `query_` function like `postgresql-simple` however it fails to expose the analogous `execute_`.

I think this function should be added.

**Comment by reiddraper** [comment]
Happy to merge this. Make a PR, please?

**Comment by jfischoff** [comment]
I've made the change locally ... and it will be trivial to make the pull request as soon as my prior request is accepted ... assuming that is still in the works ;)

**Comment by reiddraper** [comment]
@jfischoff excellent. I've just merged #13.

**Comment by jfischoff** [comment]
:)
